### ISSUE TITLE
Synchrotron Curvature

### ISSUE THREAD

**Issue by brandonshensley** [galsci/pysm#105]
Opening a new issue to discuss the synchrotron curvature parameter, which may affect the design of the Simulation Suite (#103). We have gotten some feedback that synchrotron spectral complexity is a high priority concern.

The s3 model has curvature as a single global parameter. I propose considering a new synchrotron model that has the amplitude and beta improvements of s5 but that also includes curvature. This could be implemented as a global mean value in agreement with s3, but with fluctuations following the same power spectrum as synchrotron beta in s5. That leaves only the amplitude of fluctuations to be decided, and unfortunately current data are not informative here. We could iterate starting with something modest like a 10% standard deviation around the mean at ~1 degree scales and then refine if that produces something either too extreme or completely unnoticeable.

Thoughts very much welcome @NicolettaK, @seclark, @zonca, @giuspugl, @bthorne93, others.

**Comment by giuspugl** [comment]
Hi all, 
I started addressing  this issue in order to have a _data driven_ modelling  of the synchrotron curvature.  
Below the steps i followed : 
-  use the same   template we adopted to modulate synchrotron small scales, i.e.  HASLAM map  rescaled it at 23 GHz, transformed in log pol tens `i`  and smoothed at 5 deg (see https://github.com/galsci/pysm/pull/98) 
- Normalize the  template with MinMax rescaling  so that we match the measurements of [Kogut 2012 ](https://iopscience.iop.org/article/10.1088/0004-637X/753/2/110) **within the ARCADE observational footprint**. Notice that these data are  used also in PySM2 ( Thorne et al 2016 ), i.e. `C = -0.052 \pm  0.005`. 

![image](https://user-images.githubusercontent.com/8957029/152970599-c5161576-9e73-4fbc-82be-1e922ebf4621.png)
Which is a good approximation to the one shown in Kogut 2012 (fig. 4) 
![Screen Shot 2022-02-08 at 11 38 50 AM](https://user-images.githubusercontent.com/8957029/152970841-e6dabbc7-dbda-4fea-8c35-47da268095ca.png)

The full sky map of synchrotron curvature obtained with this approach is shown below : 
![image](https://user-images.githubusercontent.com/8957029/152971022-283efe81-9b72-4256-8fbc-14a69db33159.png)

 Please let me know if this sounds to you a reasonable approach.

**Comment by NicolettaK** [comment]
This is great @Giuseppe! Should we think about adding also Gaussian small scales with slope as the one we use for the beta_s?

**Comment by brandonshensley** [comment]
Agreed, really nice analysis @giuspugl! I agree with @NicolettaK that we should add in the small scales using the slope of the beta_s power spectrum.

**Comment by giuspugl** [comment]
Ok , i've included the small scales following the power law spectral index we fit for Bs with the SPASS data, i.e. `gamma = -2.86` .  I modulate small scales of  curvature parameter `Cs` with exactly the same modulation map we adopted for Bs . 
Below you can find the power spectra 
![image](https://user-images.githubusercontent.com/8957029/153162386-c45fa1ab-523a-4bde-88a5-e802e993ed30.png)

NB: The injection of small scales doesn't affect the global properties of the Cs mpa as expected,   after that  we are  still consistent with  the Kogut 2012 measurements.

**Comment by brandonshensley** [comment]
This looks great @giuspugl!

**Comment by zonca** [comment]
when you think this is complete, you can add a Jupyter Notebook with the final analysis in a gist and I can pick up from there

**Comment by zonca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Synchrotron curvature PySM 3](https://trello.com/c/UTE1Yewe/321-synchrotron-curvature-pysm-3)

**Comment by zonca** [comment]
thanks @giuspugl, I can reproduce the notebook.

Now, my plan would be:

* execute the notebook at 8192 and create the usual maps at 2048, 4096 and 8192 for `C_s` with small scales
* create the `s7` model, similar to `s3` (https://github.com/galsci/pysm/blob/main/pysm3/data/presets.cfg#L216-L228), but with the new IQU templates and beta_s from `s5` and this `C_s` map.
* I would wait for someone to ask for it before creating a "small-scales-on-the-fly" model, I am worried otherwise we would have too many models.

@brandonshensley @NicolettaK @seclark ?
